# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_remove_publication_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='pub_date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
