# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_author_sciper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='doi',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
