# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='imported_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.ManyToManyField(blank=True, to='publications.Author'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='doi',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pub_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
