# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_auto_20170302_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
