# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_publication_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='created_at',
        ),
        migrations.AddField(
            model_name='publication',
            name='timestamp',
            field=models.FloatField(default=1491297547.400049),
            preserve_default=False,
        ),
    ]
