# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_auto_20170404_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='timestamp',
            field=models.IntegerField(),
        ),
    ]
